backend:
  name: git-gateway
  repo: ttngocthao/gatsby-netlify-cms.git
  branch: master
media_folder: /public/images
public_folder: /images

collections:
  - name: products
    label: Products
    folder: src/data/products
    create: true
    slug: "{{productName}}--{{productId}}__{{day}}-{{month}}-{{year}}"
    fields:
      - {
          name: slug,
          widget: hidden,
          label: slug,
          default: "{{productName}}-{{productId}}-{{day}}-{{month}}-{{year}}",
        }
      - {
          name: templateKey,
          widget: hidden,
          label: Template Key,
          default: products,
        }
      - { label: Product Id, name: productId, widget: string }
      - { label: Product Name, name: productName, widget: string }
      - { label: Product Intro, name: productIntro, widget: string }
      - {
          label: Product Image,
          name: productImage,
          widget: image,
          required: false,
        }
      - {
          label: Product Page Content,
          name: body,
          widget: markdown,
          required: false,
        }
  - name: pages
    label: Pages
    files:
      - file: src/data/pages/home/index.md
        label: Home Page
        name: homePage
        media_folder: ""
        public_folder: ""
        fields:
          - {
              name: "templateKey",
              widget: hidden,
              label: "Template Key",
              default: "index-page",
            }
          - { label: Page Title, name: pageTitle, widget: string }
          - {
              label: Page Introduction,
              name: pageIntroduction,
              widget: list,
              fields: [{ label: Paragraph, name: paragraph, widget: string }],
            }
